# Generated by Django 5.1.5 on 2025-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=32),
        ),
    ]
