# Generated by Django 5.1.5 on 2025-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_feedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='Booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
