# Generated by Django 5.1.5 on 2025-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_booktable_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Total_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
